/** Default buyers for local storage — edit `SEED_BUYERS` to change the seed list. */
export const SEED_BUYERS: any[] = [
  {
    id: 'buyer-northeast-medical-exchange',
    firstName: 'Northeast',
    lastName: 'Medical Exchange',
    email: '',
    paymentEmail: 'Purchasing@northeastmedicalexchange.com',
    phone: '603-303-8424 ext 1204',
    address: '2 Commerce Drive, Unit 105',
    city: 'Bedford',
    state: 'NH',
    zipCode: '03110',
    country: 'USA',
    priceSheetUrl:
      'https://docs.google.com/spreadsheets/d/e/2PACX-1vQJpkhoS4fyLt5tT560ddH_ukGnLEe0oz4SfCghLkWzqSf9hOOHBbfs0hZGzQvrhWCc1R0moWMCuxud/pubhtml',
    bestFormOfContact: 'Email (Phone Number to Introduce)',
    facebookLink: 'Contact Email Only - LSouza@NortheastMedical.com',
    removeLabels: false,
    reachOutPriorToInvoicing: false,
    paymentMethods: 'PayPal, Wire, ACH',
    isPreferred: true,
    notes: '',
    isActive: true,
  },
  {
    id: 'buyer-charles-harris',
    firstName: 'Charles',
    lastName: 'Harris',
    email: '',
    paymentEmail: 'Diabeticteststripguys@gmail.com',
    phone: '510-405-4569',
    address: '23 Maine Avenue, #94',
    city: 'Richmond',
    state: 'CA',
    zipCode: '94804',
    country: 'USA',
    priceSheetUrl: 'Text "pricesheet" to 510-405-4569',
    bestFormOfContact: 'Text',
    facebookLink: 'Text Phone Number for Price Sheet or Support',
    removeLabels: true,
    reachOutPriorToInvoicing: false,
    paymentMethods: 'PayPal, Venmo, CashApp and Zelle',
    isPreferred: true,
    notes: 'The Diabetic Test Strip Guys',
    isActive: true,
  },
  {
    id: 'buyer-chris-sampson',
    firstName: 'Chris',
    lastName: 'Sampson',
    email: 'Chris@firstclassmedsupply.com',
    paymentEmail: 'BCDeacon31@gmail.com',
    phone: '267-982-4471',
    address: '2560 Frankford Avenue STORE',
    city: 'Philadelphia',
    state: 'PA',
    zipCode: '19125',
    country: 'USA',
    priceSheetUrl: 'https://docs.google.com/spreadsheets/d/1Y6J9TVs5n8CtmLr5CckOpjkJgQTCkRLS/edit#gid=732569512',
    bestFormOfContact: 'Email',
    facebookLink: 'https://www.facebook.com/chris.sampson.10',
    removeLabels: true,
    reachOutPriorToInvoicing: true,
    paymentMethods: 'Bank ACH, Wire, Cash App, PayPal and PayPal Friends & Family',
    isPreferred: false,
    notes: 'First Class Med Supply',
    isActive: true,
  },
  {
    id: 'buyer-path-medical-supply',
    firstName: 'PATH',
    lastName: 'MEDICAL SUPPLY',
    email: '',
    paymentEmail: 'payments@pathmedicalsupply.com',
    phone: '405-965-8799',
    address: '299 W Camino Gardens Blvd, Suite 303',
    city: 'Boca Raton',
    state: 'FL',
    zipCode: '33432',
    country: 'USA',
    priceSheetUrl:
      'https://docs.google.com/spreadsheets/d/1BLRws5kaYvV78_YK10JqjP8SxPXXwdLQm3sqkEGYar4/edit?usp=sharing',
    bestFormOfContact: 'Text',
    facebookLink:
      'https://www.facebook.com/people/Sheldon-Clarke/pfbid0icQkwcESAN1gDtbnG9vKx2z4wNA8YYMB7AnxPDvwLCMoQdod4bXK6JDsihJaaR81l/',
    removeLabels: false,
    reachOutPriorToInvoicing: true,
    paymentMethods: 'PrePayment only with PayPal - On Arrival - ACH, Wire, Zelle, Check',
    isPreferred: true,
    notes: 'Formally known as Test Strip Bank',
    isActive: true,
  },
  {
    id: 'buyer-ralphel-walton',
    firstName: 'Ralphel',
    lastName: 'Walton',
    email: '',
    paymentEmail: 'sales@prestigemedicalsupply.net',
    phone: '615-669-1243',
    address: '871 Seven Oaks Blvd, Suite 240',
    city: 'Smyrna',
    state: 'TN',
    zipCode: '37167',
    country: 'USA',
    priceSheetUrl:
      'https://docs.google.com/spreadsheets/d/1uhuQ1ovm1-NIizrU2HP8AM8UcVW5qOFQbewWL8DwyEk/edit#gid=1760226217',
    bestFormOfContact: 'Email or Text',
    facebookLink: 'https://www.facebook.com/Ralphelwal',
    removeLabels: true,
    reachOutPriorToInvoicing: true,
    paymentMethods: 'Wire, Venmo, ACH, PayPal PrePayment, Cash App, Apple Pay and Zelle',
    isPreferred: false,
    notes: 'Buys short date boxes; buys expired boxes; buys damaged boxes',
    isActive: true,
  },
  {
    id: 'buyer-max-med-distributors',
    firstName: 'Max',
    lastName: 'Med Distributors',
    email: '',
    paymentEmail: 'admin@maxmeddistributors.com',
    phone: '760-448-0224',
    address: '3210 Production Avenue, Suite D',
    city: 'Oceanside',
    state: 'CA',
    zipCode: '92056',
    country: 'USA',
    priceSheetUrl:
      'https://docs.google.com/spreadsheets/d/1g0eMRGH9fkRPJaXrApZwS9MbhEDX0TR9JWLnXllyGC4/edit?gid=73038629#gid=73038629',
    bestFormOfContact: 'Text or Email',
    facebookLink: 'https://www.facebook.com/erik.gabriel.1428?mibextid=LQQJ4d',
    removeLabels: true,
    reachOutPriorToInvoicing: true,
    paymentMethods: 'PayPal prepaid or Zelle, ACH, Wire, Venmo, Cash App or Check after delivery',
    isPreferred: false,
    notes: 'If you cannot remove labels, let us know; may send invoice.',
    isActive: true,
  },
];
